name: Deploy Day4

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload Day4 Folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./day4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4